# Generated by Django 4.0.3 on 2022-03-07 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0002_keyword_rename_rooms_room_keywordsearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordsearch',
            options={'verbose_name': 'Keyword Search', 'verbose_name_plural': 'Keywords Search'},
        ),
        migrations.RenameField(
            model_name='keywordsearch',
            old_name='register_on',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='keywordsearch',
            name='count',
        ),
        migrations.AddField(
            model_name='keywordsearch',
            name='total_search',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_keyword_users', to='search.keyword'),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='keywordsearch',
            constraint=models.UniqueConstraint(fields=('user', 'keyword'), name='user_keyword_unique'),
        ),
    ]
